services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:80"
    volumes:
      - .:/java
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://related:java7834@db:5432/fastapi_db
      - REDIS_URL=redis://redis_cache:6379/0
      - PYTHONPATH=/java
      - WATCHFILES_FORCE_POLLING=true 
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    environment:
      - POSTGRES_USER=related
      - POSTGRES_PASSWORD=java7834
      - POSTGRES_DB=fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: