services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/fastapi_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    environment:
      - POSTGRES_USER=related
      - POSTGRES_PASSWORD=java7834
      - POSTGRES_DB=fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
volumes:
  postgres_data: